from flask import Flask, render_template, request
import pickle
import numpy as np

app = Flask(__name__)


def prediction(lst):
    filename = 'model/rfmodel.pkl'
    with open(filename, 'rb') as file:
        model = pickle.load(file)
    pred_log_value = model.predict([lst])[0]
    pred_value = np.exp(pred_log_value) - 1
    return pred_value


@app.route('/', methods=['POST', 'GET'])
def index():
    pred_value = 0
    if request.method == 'POST':
        Brand = request.form['Brand']
        Model = request.form['Model']
        Kilometers = request.form['Kilometers']
        EngineCapacity = request.form['EngineCapacity']
        Length = request.form['Length']
        Width = request.form['Width']
        SeatingCapacity = request.form['SeatingCapacity']
        FuelCapacity = request.form['FuelCapacity']
        CarAge = request.form['CarAge']
        PowerValue = request.form['PowerValue']
        TorqueValue = request.form['TorqueValue']
        FuelType = request.form['FuelType']
        Transmission = request.form['Transmission']
        Owner = request.form['Owner']
        Drivetrain = request.form['Drivetrain']

        feature_list = []

        min_max_values = {
            'Kilometers': (8000, 109000),
            'EngineCapacity': (998, 2987),
            'Length': (3565, 4936),
            'Width': (1495, 2031),
            'SeatingCapacity': (5, 7),
            'FuelCapacity': (35, 80),
            'CarAge': (2, 23),
            'PowerValue': (67, 248),
            'TorqueValue': (90, 500)
        }

        def normalize(value, feature_name, min_max_values):
            min_val, max_val = min_max_values[feature_name]
            return (value - min_val) / (max_val - min_val)

        feature_list.append(normalize(float(Kilometers),
                            'Kilometers', min_max_values))
        feature_list.append(normalize(float(EngineCapacity),
                            'EngineCapacity', min_max_values))
        feature_list.append(normalize(float(Length), 'Length', min_max_values))
        feature_list.append(normalize(float(Width), 'Width', min_max_values))
        feature_list.append(normalize(int(SeatingCapacity),
                            'SeatingCapacity', min_max_values))
        feature_list.append(normalize(float(FuelCapacity),
                            'FuelCapacity', min_max_values))
        feature_list.append(normalize(int(CarAge), 'CarAge',
                            min_max_values))  # CarAge is an int
        feature_list.append(normalize(float(PowerValue),
                            'PowerValue', min_max_values))
        feature_list.append(normalize(float(TorqueValue),
                            'TorqueValue', min_max_values))

        brand_list = ['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Ferrari', 'Fiat', 'Ford', 'Honda', 'Hyundai', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Lamborghini', 'Land Rover', 'Lexus', 'MG', 'MINI',
                      'Mahindra', 'Maruti Suzuki', 'Maserati', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Porsche', 'Renault', 'Rolls-Royce', 'Skoda', 'Ssangyong', 'Tata', 'Toyota', 'Volkswagen', 'Volvo']
        model_list = ['2 Series',
                      '3-Series 320d',
                      '3-Series 320i',
                      '3-Series 330i',
                      '488 GTB',
                      '5-Series 520d',
                      '5-Series 525d',
                      '5-Series 530d',
                      '5-Series 530i',
                      '6-Series GT',
                      '7-Series 730Ld',
                      '718 Boxster',
                      '718 Cayman',
                      '911 Carrera',
                      'A-Class A',
                      'A-Class Sedan',
                      'A3 35',
                      'A3 40',
                      'A4 1.8',
                      'A4 2.0',
                      'A4 30',
                      'A4 35',
                      'A4 Premium',
                      'A6 2.0',
                      'A6 3.0',
                      'A6 35',
                      'A6 Technology',
                      'A7 Sportback',
                      'A8 3.0',
                      'Accent Executive',
                      'Accord 2.4',
                      'Alcazar Platinum',
                      'Alcazar Prestige',
                      'Alcazar Signature',
                      'Alto 800',
                      'Alto LXi',
                      'Alto VXI',
                      'Alto VXi',
                      'Altroz XT',
                      'Alturas G4',
                      'Amaze 1.2',
                      'Amaze 1.5',
                      'Amaze VX',
                      'Ameo Highline1.2L',
                      'Ameo Trendline',
                      'Aspire Titanium',
                      'Aspire Titanium1.5',
                      'Astor Sharp',
                      'Aura S',
                      'B-class B180',
                      'BR-V V',
                      'Baleno Alpha',
                      'Baleno Delta',
                      'Baleno Sigma',
                      'Baleno Zeta',
                      'Beat LT',
                      'Bolero Power',
                      'Bolero SLE',
                      'Bolero SLX',
                      'Brio E',
                      'Brio EX',
                      'Brio S',
                      'Brio V',
                      'Brio VX',
                      'C-Class 200',
                      'C-Class 220',
                      'C-Class 250',
                      'C-Class C',
                      'C-Class C200',
                      'C-Class C220d',
                      'C-Class Cabriolet',
                      'C-Coupe 43',
                      'CLA 200',
                      'CLS 300d',
                      'CR-V 2.0L',
                      'CR-V 2.4',
                      'Camry 2.5L',
                      'Camry Hybrid',
                      'Captiva LTZ',
                      'Carnival Limousine',
                      'Cayenne 3.2',
                      'Cayenne Base',
                      'Cayenne Coupe',
                      'Cayenne Diesel',
                      'Cayenne Platinum',
                      'Cayenne Turbo',
                      'Celerio LDi',
                      'Celerio LXi',
                      'Celerio VXi',
                      'Celerio X',
                      'Celerio ZXi',
                      'Ciaz Alpha',
                      'Ciaz Delta',
                      'Ciaz S',
                      'Ciaz VDi',
                      'Ciaz VDi+',
                      'Ciaz VXi',
                      'Ciaz ZDi',
                      'Ciaz ZXI+',
                      'Ciaz ZXi',
                      'Ciaz Zeta',
                      'City 1.5',
                      'City CVT',
                      'City E',
                      'City S',
                      'City SV',
                      'City V',
                      'City VX',
                      'City ZX',
                      'Civic 1.8S',
                      'Civic 1.8V',
                      'Commuter HiAce',
                      'Compass Limited',
                      'Compass Longitude',
                      'Compass Model',
                      'Compass Sport',
                      'Cooper D',
                      'Cooper JCW',
                      'Cooper S',
                      'Corolla Altis',
                      'Countryman Cooper',
                      'Creta 1.4',
                      'Creta 1.6',
                      'Creta E',
                      'Creta EX',
                      'Creta SX',
                      'Cruze LTZ',
                      'DZire LDi',
                      'DZire VDi',
                      'DZire VXi',
                      'DZire ZDi',
                      'DZire ZXi',
                      'Discovery 2.0',
                      'Discovery 3.0',
                      'Discovery HSE',
                      'Discovery Sport',
                      'Duster 110',
                      'Duster 85',
                      'Duster RXL',
                      'Duster RXS',
                      'E-Class 200',
                      'E-Class 280',
                      'E-Class E',
                      'E-Class E200',
                      'E-Class E220',
                      'E-Class E250',
                      'E-Class E350',
                      'ES 300h',
                      'Ecosport Ambiente',
                      'Ecosport Titanium',
                      'Ecosport Titanium+',
                      'Ecosport Trend',
                      'Eeco 5',
                      'Eeco 7',
                      'Elantra 1.6',
                      'Elantra 1.8',
                      'Elantra 2.0',
                      'Elantra SX',
                      'Elite i20',
                      'Endeavour 3.0L',
                      'Endeavour Sport',
                      'Endeavour Titanium',
                      'Endeavour Trend',
                      'Eon 1.0',
                      'Eon D-Lite',
                      'Eon Era',
                      'Eon Magna',
                      'Eon Sportz',
                      'Ertiga LXI',
                      'Ertiga VDI',
                      'Ertiga VDi',
                      'Ertiga VXI',
                      'Ertiga Vxi',
                      'Ertiga ZDI',
                      'Ertiga ZDi',
                      'Ertiga ZXI+',
                      'Ertiga ZXi',
                      'Estilo LXi',
                      'Estilo VXi',
                      'Etios 1.2',
                      'Etios G',
                      'Etios GD',
                      'Etios Liva',
                      'Etios V',
                      'Etios VXD',
                      'Evoque Dynamic',
                      'Evoque HSE',
                      'Evoque Pure',
                      'Evoque SE',
                      'F-Pace Prestige',
                      'Fabia Elegance',
                      'Fiesta Style',
                      'Fiesta Titanium',
                      'Figo Duratec',
                      'Figo Duratorq',
                      'Figo Titanium1.5',
                      'Figo Trend',
                      'Fluence 1.5',
                      'Fortuner 2.8',
                      'Fortuner 3.0',
                      'Fortuner 4x2',
                      'GL-Class 350',
                      'GLA 200',
                      'GLA 220',
                      'GLC 200',
                      'GLC 220',
                      'GLC 220d',
                      'GLE 250',
                      'GLE 300d',
                      'GLE 350',
                      'GLE 43',
                      'GLS 350',
                      'GLS 400',
                      'GLS 400d',
                      'GLS 450',
                      'Ghost 6.5',
                      'Ghost Extended',
                      'Glanza G',
                      'Glanza V',
                      'Gloster Savvy',
                      'Gloster Sharp',
                      'Go D',
                      'Go Plus',
                      'Go T',
                      'Grand Vitara',
                      'Grand i10',
                      'Grande GX',
                      'Harrier XT',
                      'Harrier XZ',
                      'Harrier XZA',
                      'Hector Plus',
                      'Hector Sharp',
                      'Hexa XE',
                      'Hexa XM',
                      'Hexa XT',
                      'Hexa XTA',
                      'Huracan LP',
                      'Ignis Delta',
                      'Ignis Zeta',
                      'Ikon DuraTorq',
                      'Innova 2.0',
                      'Innova 2.4',
                      'Innova 2.5',
                      'Innova 2.7',
                      'Innova 2.8',
                      'Innova GX',
                      'Innova ZX',
                      'Jazz S',
                      'Jazz SV',
                      'Jazz V',
                      'Jazz VX',
                      'Jetta 1.9L',
                      'KUV100 K6',
                      'Kiger RXT',
                      'Kiger RXZ',
                      'Kodiaq L&K',
                      'Kodiaq Style',
                      'Kushaq Style',
                      'Kwid 1.0',
                      'Kwid CLIMBER',
                      'Kwid RXL',
                      'Kwid RXT',
                      'LX SUV',
                      'Levante Diesel',
                      'Linea Emotion',
                      'M-Class 350',
                      'M-Class ML',
                      'MU-X 4x2',
                      'Macan Base',
                      'Macan S',
                      'Magnite XL',
                      'Manza Aqua',
                      'Marazzo M2',
                      'Marazzo M6',
                      'Micra XV',
                      'Mobilio RS',
                      'Mobilio S',
                      'Mustang GT',
                      'NX 300h',
                      'Nano Base',
                      'Nexon EV',
                      'Nexon XM',
                      'Nexon XMA',
                      'Nexon XT',
                      'Nexon XZ',
                      'Nexon XZA',
                      'Octavia 1.8',
                      'Octavia 2.0',
                      'Octavia Elegance',
                      'Octavia RS',
                      'Octavia Style',
                      'Pajero 2.5',
                      'Pajero SFX',
                      'Pajero Select',
                      'Panamera 3.0',
                      'Polo 1.2',
                      'Polo 1.5',
                      'Polo Comfortline',
                      'Polo GT',
                      'Polo Highline',
                      'Polo Highline1.0L',
                      'Polo Highline1.2L',
                      'Polo Highline1.5L',
                      'Polo Trendline',
                      'Pulse RxL',
                      'Punch Creative',
                      'Punto Active',
                      'Q2 Premium',
                      'Q3 2.0',
                      'Q3 30',
                      'Q3 35',
                      'Q5 2.0',
                      'Q5 3.0',
                      'Q5 35',
                      'Q5 40',
                      'Q5 45',
                      'Q7 3.0',
                      'Q7 35',
                      'Q7 45',
                      'Q7 Technology',
                      'Q8 Celebration',
                      'Quanto C4',
                      'Quanto C8',
                      'R-Class R350',
                      'RS5 4.2',
                      'Range Rover',
                      'Rapid 1.5',
                      'Rapid 1.6',
                      'Rapid Ambition',
                      'Rapid Elegance',
                      'Rapid Monte',
                      'Rapid Style',
                      'Redigo S',
                      'Redigo T(O)',
                      'Rexton RX6',
                      'Rexton RX7',
                      'Ritz Ldi',
                      'Ritz VXI',
                      'Ritz Vdi',
                      'Ritz Vxi',
                      'Ritz Zxi',
                      'S-Class 280',
                      'S-Class 300',
                      'S-Class 350',
                      'S-Class 500L',
                      'S-Class Maybach',
                      'S-Class S',
                      'S-Cross Alpha',
                      'S-Cross Delta',
                      'S-Cross Sigma',
                      'S-Cross Zeta',
                      'S-Presso VXi',
                      'S60 Kinetic',
                      'S90 D4',
                      'S90 Momentum',
                      'SLK-Class SLK',
                      'SX4 VXi',
                      'SX4 ZDI',
                      'Safari 2.2',
                      'Safari 4x2',
                      'Safari XZ',
                      'Safari XZA',
                      'Sail Sedan',
                      'Santa Fe',
                      'Santro Era',
                      'Santro GL',
                      'Santro GLS',
                      'Santro Magna',
                      'Santro Sportz',
                      'Santro XO',
                      'Scorpio 2.6',
                      'Scorpio LX',
                      'Scorpio S10',
                      'Scorpio S11',
                      'Scorpio S2',
                      'Scorpio S3',
                      'Scorpio S4',
                      'Scorpio S5',
                      'Scorpio S6',
                      'Scorpio S9',
                      'Scorpio SLE',
                      'Scorpio VLX',
                      'Seltos GTX',
                      'Seltos HTK',
                      'Seltos HTX',
                      'Sonata 2.0',
                      'Sonet GTX',
                      'Spark LS',
                      'Sunny XL',
                      'Sunny XV',
                      'Superb Elegance',
                      'Superb L&K',
                      'Superb Sportline',
                      'Superb Style',
                      'Swift DZire',
                      'Swift LXi',
                      'Swift Lxi',
                      'Swift VDi',
                      'Swift VXi',
                      'Swift ZDi',
                      'Swift ZXi',
                      'TT 2.0',
                      'TUV300 T10',
                      'TUV300 T6',
                      'TUV300 T8',
                      'Taigun Highline',
                      'Teana 250XL',
                      'Terrano XE',
                      'Terrano XL',
                      'Terrano XV',
                      'Thar AX',
                      'Thar CRDe',
                      'Thar LX',
                      'Tiago NRG',
                      'Tiago Revotron',
                      'Tigor EV',
                      'Tigor Revotorq',
                      'Tigor Revotron',
                      'Tigor XZA',
                      'Tiguan AllSpace',
                      'Tiguan Highline',
                      'Tucson 2WD',
                      'Tucson GL',
                      'Tucson GLS',
                      'Urban Cruiser',
                      'V-Class Elite',
                      'V40 Cross',
                      'V40 D3',
                      'Vellfire Hybrid',
                      'Vento Comfortline',
                      'Vento Highline',
                      'Vento TSI',
                      'Vento Trendline',
                      'Venue S',
                      'Venue SX',
                      'Verna 1.6',
                      'Verna EX',
                      'Verna Fluidic',
                      'Verna SX',
                      'Vitara Brezza',
                      'WR-V S',
                      'WR-V VX',
                      'Wagon R',
                      'Wrangler Rubicon',
                      'X1 sDrive20d',
                      'X1 sDrive20i',
                      'X1 xDrive20d',
                      'X3 20d',
                      'X3 xDrive',
                      'X3 xDrive-20d',
                      'X3 xDrive20d',
                      'X3 xDrive30i',
                      'X4 xDrive30d',
                      'X5 3.0d',
                      'X5 xDrive',
                      'X5 xDrive30d',
                      'X6 xDrive40i',
                      'X7 xDrive40i',
                      'XC40 D4',
                      'XC40 T4',
                      'XC60 Inscription',
                      'XC90 D5',
                      'XE Prestige',
                      'XF 3.0',
                      'XF Portfolio',
                      'XF Prestige',
                      'XF R',
                      'XJ 3.0',
                      'XL6 Alpha',
                      'XL6 Zeta',
                      'XUV300 1.5',
                      'XUV300 W8',
                      'XUV500 W10',
                      'XUV500 W11',
                      'XUV500 W4',
                      'XUV500 W5',
                      'XUV500 W6',
                      'XUV500 W7',
                      'XUV500 W8',
                      'XUV500 W9',
                      'XUV700 AX',
                      'Xcent E',
                      'Xcent S',
                      'Xcent SX',
                      'Xylo D2',
                      'Xylo D4',
                      'Yaris J',
                      'Yaris V',
                      'ZS EV',
                      'Zen LX',
                      'Zen LXi',
                      'Zest XE',
                      'Zest XM',
                      'i10 1.1L',
                      'i10 Asta',
                      'i10 Era',
                      'i10 Magna',
                      'i10 Sportz',
                      'i20 Active',
                      'i20 Asta',
                      'i20 Magna',
                      'i20 Sportz']

        fuel_list = ['CNG', 'Diesel', 'Electric', 'Hybrid', 'LPG', 'Petrol']
        transmission_list = ['Automatic', 'Manual']
        owner_list = ['First', 'More than 3', 'Second']
        Drivetrain_list = ['AWD', 'FWD', 'RWD']

        def traverse_list(lst, value):
            for item in lst:
                if item == value:
                    feature_list.append(1)
                else:
                    feature_list.append(0)

        traverse_list(brand_list, Brand)
        traverse_list(model_list, Model)
        traverse_list(fuel_list, FuelType)
        traverse_list(transmission_list, Transmission)
        traverse_list(owner_list, Owner)
        traverse_list(Drivetrain_list, Drivetrain)

        pred_value = prediction(feature_list)
        pred_value = round(pred_value, 2)

    return render_template('index.html', pred_value=pred_value)


if __name__ == '__main__':
    app.run(debug=True)
